### ISSUE TITLE
Timezone Issue on MacOS

### ISSUE THREAD

**Issue by kdekorte** [bmillham/starlink-graph#1]
After cloning and trying to run I get this..

➜  starlink-graph git:(main) python3 starlink-graph.py
Traceback (most recent call last):
  File "/Users/kdekorte/git/starlink-graph/starlink-graph.py", line 290, in <module>
    ani = startup()
  File "/Users/kdekorte/git/starlink-graph/starlink-graph.py", line 275, in startup
    sd.outages()
  File "/Users/kdekorte/git/starlink-graph/starlinkdata.py", line 104, in outages
    fix = self._gps_to_gmt(o.start_timestamp_ns)
  File "/Users/kdekorte/git/starlink-graph/starlinkdata.py", line 65, in _gps_to_gmt
    return leapseconds.gps_to_utc(datetime.datetime(1980,1,6) +
  File "/Users/kdekorte/git/starlink-graph/leapseconds.py", line 229, in gps_to_utc
    return tai_to_utc(gps_to_tai(gps_time))
  File "/Users/kdekorte/git/starlink-graph/leapseconds.py", line 219, in tai_to_utc
    return tai_time - dTAI_UTC_from_tai(tai_time)
  File "/Users/kdekorte/git/starlink-graph/leapseconds.py", line 181, in dTAI_UTC_from_tai
    return _dTAI_UTC(tai_time, lambda ls: ls.utc + ls.dTAI_UTC)
  File "/Users/kdekorte/git/starlink-graph/leapseconds.py", line 205, in _dTAI_UTC
    leapseconds_list = leapseconds()
  File "/Users/kdekorte/git/starlink-graph/leapseconds.py", line 91, in leapseconds
    raise ValueError('Unable to open any tzfile: %s' % (tzfiles,))
ValueError: Unable to open any tzfile: ['/usr/share/zoneinfo/right/UTC', '/usr/lib/zoneinfo/right/UTC']

not sure why "right" is in the path for the tzfile

**Comment by bmillham** [comment]
I just pushed a new version that should fix this for you. The 'right/UTC' is a TZ file with the leapsecond info found on Linux. I guess that information isn't on MacOS? Or in a different place. The new version will attempt to use the UTC file and return default leapseconds if it's unable to real the LS info. I also made a change so that if the TZ files can't be found instead of returning an error it will return the fallback LSs. Please let me know if this worked for you!

**Comment by kdekorte** [comment]
Thanks Brian, that solved the problem.. tool works great for me.

**Comment by bmillham** [comment]
Great! Thanks for testing on the Mac for me. BTW, I did a little more rearching about leapseconds on the Mac and found this: There is no leap second information stored in the IANA database on macOS: /usr/share/zoneinfo
You will notice a warning right now when you run my script about no leapseconds. I will do a push to fix that now that I know for sure that the Mac file doesn't contain leapsecond info.

**Comment by bmillham** [comment]
Marking as closed.
