### ISSUE TITLE
fails to start when terminal has not been powered on for very long

### ISSUE THREAD

**Issue by joeyh** [bmillham/starlink-graph#5]
I powered on my starlink terminal 10 minutes ago, and:

```
joey@darkstar:~/tmp/starlink-graph#main>./starlink-graph.py 

(starlink-graph.py:156946): Gtk-WARNING **: 11:02:11.930: Content added to the action area of a dialog using header bars

(starlink-graph.py:156946): Gtk-WARNING **: 11:02:26.718: Content added to the action area of a dialog using header bars

(starlink-graph.py:156946): Gtk-WARNING **: 11:02:40.678: Content added to the action area of a dialog using header bars
Traceback (most recent call last):
  File "/home/joey/tmp/starlink-graph2/./starlink-graph.py", line 357, in <module>
    ani = startup()
  File "/home/joey/tmp/starlink-graph2/./starlink-graph.py", line 340, in startup
    sd.history()
  File "/home/joey/tmp/starlink-graph2/starlinkdata.py", line 86, in history
    l = {k: z[k][i] for k in z.keys()}
  File "/home/joey/tmp/starlink-graph2/starlinkdata.py", line 86, in <dictcomp>
    l = {k: z[k][i] for k in z.keys()}
IndexError: list index out of range
```

Setting history = 10 in starlink-graph.ini worked around this problem. It was 900, and I guess it expects to be able to pull 900 seconds (15 minutes) of history, which it cannot when the terminal has not been on that long.

**Comment by bmillham** [comment]
I'll have a fix for this shortly. I ran into it myself last night.

**Comment by bmillham** [comment]
I just pushed a fix for this.
